### ISSUE TITLE
Missing airport KJT in Indonesia

### ISSUE THREAD

**Issue by chakraskun** [timrogers/airports#129]
Hi airports teams,
thanks for creating this awesome gem,
currently the gem is missing airport in Indonesia called Kertajati (KJT/WICA).
it's not a brand new one, so I believe it might be missing from the OpenFlight api, since it's first flight was pre-covid.

here's the link to the
- flightradar page https://www.flightradar24.com/airport/kjt
- flightaware page https://www.flightaware.com/live/airport/WICA

thanks :beers:

**Comment by timrogers** [comment]
Closed by #130 ✅
