### ISSUE TITLE
Timezone information

### ISSUE THREAD

**Issue by kunashir** [timrogers/airports#16]
Good day!
The gem is almost that data which I need for my project but timezones look like a little bit strange. Right now this field contains offset by UTC and looks like it doesn't consider summer time shift:
```ruby
2.4.5 :002 > ham = Airports.find_by_iata_code("HAM")
 => #<Airports::Airport:0x00007fecd9810308 @name="Hamburg Airport", @city="Hamburg", @country="Germany", @iata="HAM", @icao="EDDH", @latitude="53.630401611328", @longitude="9.9882297515869", @altitude="53", @timezone="1", @dst="E">
2.4.5 :003 > ham.timezone
 => "1"
```
however:
```ruby
2.4.5 :008 > Timezone['Europe/Berlin'].utc_offset / 3600
 => 2
```
Or I didn't figure out something?

Thanks.

**Comment by timrogers** [comment]
This data comes from [OpenFlights](http://openflights.org/) so it'd be worth taking this up with them.

For what it's worth though, the data about this kind of thing is mind-boggling complex 🙈 IATA have some very hard to understand documents around it - it's called SSIM, you'll find it with some googling.

**Comment by kunashir** [comment]
Ok, thanks.
