### ISSUE TITLE
airport BER is missing 

### ISSUE THREAD

**Issue by ChenWeski** [timrogers/airports#38]
Hi there,
Can you please add BER (iata code) airport to your JSON file.
Thank you!

**Comment by timrogers** [comment]
@ChenWeski Hey! This is missing from the source data, [OpenFlights](https://raw.githubusercontent.com/jpatokal/openflights/master/data/airports.dat). You can add it yourself by making a pull request updating [`patches.dat`](https://github.com/timrogers/airports/blob/master/data/patches.dat).

**Comment by timrogers** [comment]
This has now been fixed in v1.6.1, thanks to @PavelWeSki's work in #39 🎉
